version: "3.8"

services:

  grafana:
    image: grafana/grafana:11.2.0
    volumes:
      - ../shared/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # - ../shared/pyroscope/grafana-provisioning:/etc/grafana/provisioning
      # - ../shared/pyroscope-dashboard.json:/etc/grafana/provisioning/dashboards/dashboard.json
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      # https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/feature-toggles/
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor,traceToMetrics,publicDashboards,showTraceId,pyroscopeFlameGraph,correlations
      # - GF_INSTALL_PLUGINS=pyroscope-datasource,pyroscope-panel
      - NO_PROXY=grafana,loki,minio,otel-collector,prometheus,pyroscope,tempo
    ports:
      - "3000:3000"

  loki:
    image: grafana/loki:3.2.0
    command: "-config.file=/etc/loki/local-config.yaml"
    environment:
      - NO_PROXY=grafana,loki,minio,otel-collector,prometheus,pyroscope,tempo
    ports:
      - "3100:3100"
      - 7946
      - 9095
    volumes:
      - ../shared/loki.yaml:/etc/loki/local-config.yaml
    depends_on:
      - minio
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3100/ready || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2024-09-22T00-33-43Z
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /data/loki-data && \
        mkdir -p /data/loki-ruler && \
        minio server /data
    environment:
      - MINIO_ROOT_USER=loki
      - MINIO_ROOT_PASSWORD=supersecret
      - MINIO_PROMETHEUS_AUTH_TYPE=public
      - MINIO_UPDATE=off
      - NO_PROXY=grafana,loki,minio,otel-collector,prometheus,pyroscope,tempo
    ports:
      - 9000
    volumes:
      - ./minio-data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 15s
      timeout: 20s
      retries: 5

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.96.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ../shared/otel-collector.yaml:/etc/otel-collector.yaml
      - /var/log:/var/log
      - "../../../../:/app:r"
    ports:
      - "4317:4317"   # otlp grpc
      - "4318:4318"   # otlp http
      - "8094:8094"   # syslog
    environment:
      - NO_PROXY=grafana,loki,minio,otel-collector,prometheus,pyroscope,tempo
    depends_on:
      - loki
      - prometheus
      - tempo

  prometheus:
    image: prom/prometheus:v2.54.1
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ../shared/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
    environment:
      - NO_PROXY=grafana,loki,minio,otel-collector,prometheus,pyroscope,tempo

  pyroscope:
    image: pyroscope/pyroscope:0.37.2
    ports:
      - "4040:4040"
    command:
      - server
    environment:
      - NO_PROXY=grafana,loki,minio,otel-collector,prometheus,pyroscope,tempo
      - PYROSCOPE_LOG_LEVEL=info
      - PYROSCOPE_WAIT_AFTER_STOP=true

  tempo:
    image: grafana/tempo:2.6.0
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ../shared/tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      # - "4317:4317"   # otlp grpc
      # - "4318:4318"   # otlp http
      - "14268:14268" # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095"   # tempo grpc
      - "9411:9411"   # zipkin
    environment:
      - NO_PROXY=grafana,loki,minio,otel-collector,prometheus,pyroscope,tempo
